const prompt = require("prompt-sync")({sugint: true});
//---------------------punto1------------------
let num = prompt("ingrese numero entero")

function doble(){
    return  num * 2
}
console.log(doble())
/*
//----------------------------------------------
let num1 = prompt("ingrese numero entero 1: ");
let num2 = prompt("ingrese numero entero 2: ");
console.log (resultado(num1, num2))

function resultado(num1,num2){
    return  num1 * num2
}

//-------------------------------------
let num1 = prompt("ingrese numero entero 1: ");

if (num1 <= 0){console.log("naaa");
} else if (num1 > 0){console.log("eso tilin");}

let num2 = prompt("ingrese numero entero 2: ");

if (num2 <= 0){console.log("naaa");
} else if (num2 > 0){console.log("eso tilin");}
console.log(divicion(num1 , num2))
function divicion(num1,num2){
    
    return  num1 / num2
}
//---------punto 2-------------------

let ciclista = {
    nombre :'',
    apellido : '',
    edad : '',
    tieneBici : 
    

};*/



